# -*- coding: utf-8 -*-
"""TP03-19921122.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17JlCswi1fWLz2E9NZWjaiXX16gnrkWMO

Identitas
"""

# Nama      : Salma Sari Juliani
# NIM       : 19921122
# Deskripsi : Tugas Pendahuluan Modul 3

"""Code"""

import pandas as pd
data_frame = pd.read_csv('pokemon.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows' , None)
data_frame.head()

# 1. Banyaknya (panjangnya) data
print(len(data_frame))

# 2. Data ke-100 hingga ke-120 (indeks 99 hingga indeks 119)
data_frame[99:120]

# 3. Data pada kolom total_points sampai dengan base_experience
data_frame.loc[ : , 'total_points':'base_experience']

# 4. Data pokemon dengan name Pikachu
data_frame.loc[data_frame['name'] == 'Pikachu']

# 5.a. Data dengan height maksimum 
height_maksimum = data_frame['height'].idxmax()
data_frame[height_maksimum:height_maksimum+1]

# 5.b. Data dengan height minimum 
height_minimum = data_frame['height'].idxmin()
data_frame[height_minimum:height_minimum+1]

# 6. Jangkauan dari kolom weight
maksimum = data_frame.max()
minimum = data_frame.min()
range = maksimum['weight'] - minimum['weight']
range

# 7. Data yang diurutkan berdasarkan kolom total_points secara menaik
data_frame.sort_values(['total_points'], ascending=[1])

# 8. Tabel frekuensi munculnya nilai kolom status
data_frame['status'].value_counts()

# 9. Kelompokkan data berdasarkan kolom status dan type, kemudian tampilkan rata-rata kolom attack-nya
data_frame.groupby(['status', 'type'])['attack'].mean()

# 10. Rata-rata dari kolom hp
data_frame['hp'].mean()

# 11. Pandang kolom catch_rate, base_friendship, dan base_experience. Dengan kolom manakah catch_rate berkorelasi? Berapa koefisien korelasinya?
data_frame['catch_rate'].corr(data_frame['base_experience'])